#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "common.h"

Instruction instructions[258] = 
{
    {   .name = "trap",     .arity = { 3, 2, 1}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 1},
                            { 1, 1, 1},
                            { 1, 1, 1}}},
    {   .name = "fcmp",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fun",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "feql",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fadd",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fix",      .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fsub",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fixu",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "flot",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "floti",    .arity = { 3, 2, 0}, .has_alt_ver = false, // ? is this correct
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "flotu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "flotui",   .arity = { 3, 2, 0}, .has_alt_ver = false, // ?
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "sflot",    .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sfloti",   .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "sflotu",   .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sflotui",  .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "fmul",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fcmpe",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fune",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "feqle",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fdiv",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fsqrt",    .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "frem",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fint",     .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mul",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "muli",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mulu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mului",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "div",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "divi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "divu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "divui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "add",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "addi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "addu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "addui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sub",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "subi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "subu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "subui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "2addu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "2addui",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "4addu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "4addui",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "8addu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "8addui",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "16addu",   .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "16addui",  .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmp",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmpi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmpu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmpui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "neg",      .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "negi",     .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "negu",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "negui",    .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "sl",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sli",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "slu",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "slui",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sr",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sri",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sru",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "srui",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bn",       .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnb",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bz",       .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bzb",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bp",       .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bpb",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bod",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bodb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnn",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnnb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnz",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnzb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnp",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bnpb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bev",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bevb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbn",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbz",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbzb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbp",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbpb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbod",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbodb",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnn",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnnb",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnz",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnzb",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnp",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbnpb",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbev",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pbevb",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csn",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csni",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csz",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cszi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csp",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cspi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csod",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csodi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csnn",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csnni",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csnz",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csnzi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csnp",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csnpi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    { .name = "csev",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "csevi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsn",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsni",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsz",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zszi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsp",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zspi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsod",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsodi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsnn",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsnni",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsnz",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsnzi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsnp",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsnpi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsev",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "zsevi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldb",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldbi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldbu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldbui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldw",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldwi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldwu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldwui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldt",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldti",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldtu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldtui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldo",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldoi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldou",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldoui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldsf",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "ldsfi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldht",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "ldhti",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cswap",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cswapi",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldunc",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldunci",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldvts",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ldvtsi",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "preld",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "preldi",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "prego",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pregoi",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "go",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "goi",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stb",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stbi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stbu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stbui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stw",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stwi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stwu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stwui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stt",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stti",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sttu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sttui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sto",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stoi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    { .name = "stou",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stoui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stsf",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "stsfi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stht",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sthti",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stco",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stcoi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stunc",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "stunci",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "syncd",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "syncdi",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "prest",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "presti",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "syncid",   .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "syncidi",  .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pushgo",   .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pushgoi",  .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "or",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ori",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "orn",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "orni",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "nor",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "nori",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "xor",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "xori",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "and",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andn",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andni",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "nand",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "nandi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "nxor",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "nxori",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bdif",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "bdifi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "wdif",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "wdifi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "tdif",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "tdifi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "odif",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "odifi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mux",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "muxi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sadd",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "saddi",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mor",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mori",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mxor",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mxori",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "seth",     .arity = { 2, 0 ,0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "setmh",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "setml",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "setl",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "inch",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "incmh",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "incml",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "incl",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "orh",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ormh",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "orml",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "orl",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andnh",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andnmh",   .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andnml",   .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "andnl",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "jmp",      .arity = { 1, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "jmpb",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pushj",    .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pushjb",   .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "geta",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "getab",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "put",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "puti",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "pop",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "resume",   .arity = { 1, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "save",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}}, // ?
    {   .name = "unsave",   .arity = { 1, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sync",     .arity = { 1, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "swym",     .arity = {3, 2, 1}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 1},
                            { 1, 1, 0},
                            { 1, 0, 0}}}, // NOP
    {   .name = "get",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "trip",     .arity = {3, 2, 1}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 1},
                            { 1, 1, 0},
                            { 1, 0, 0}}},
    {   .name = "lda",      .arity = {3, 0, 0}, .has_alt_ver = false, 
        .is_constant = {    { 1, 1, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "set",      .arity = {2, 2, 0}, .has_alt_ver = false,
        .is_constant = {    {1, 0, 0},
                            {1, 1, 0},
                            {0, 0, 0}}},
};

int32_t parseNumber(char* buffer)
{
    int32_t number = 0;

    if (sscanf(buffer, "%d", &number) == 1)
        return number;

    return -1;
}

char* getString(char* buffer, int32_t length, int32_t buf_index)
{
    if(length <= 1)
        return NULL;
    
    int32_t i = 0;
    char* new_string = (char*)malloc(length * sizeof(char));
    new_string[length - 1] = '\0';
    for(; (i + 1 - length) != 0; i++)
    {
        new_string[i]   = buffer[buf_index - length + 1 + i];   
    }

    return new_string;
}

char* readFile(const char* path)
{
    FILE* fd = fopen(path, "rb");
    if(fd == NULL)
    {
        fprintf(stderr, "Could not open file \"%s\" for reading.\n", path);
        exit(74);
    }

    fseek(fd, 0L, SEEK_END);
    size_t file_size = ftell(fd);
    rewind(fd);

    char* buffer = (char*)malloc(file_size + 1);
    if(buffer == NULL)
    {
        fprintf(stderr, "Not enough memory to read \"%s\".\n", path);
        exit(74);
    }

    size_t bytes_read = fread(buffer, sizeof(char), file_size, fd);
    if (bytes_read < file_size)
    {
        fprintf(stderr, "Could not read file \"%s\".\n", path);
        exit(74);
    }

    buffer[bytes_read] = '\0';

    fclose(fd);
    return buffer;
}

FILE* createFile(const char* path)
{
    FILE* fd = fopen(path, "w");
    if (fd == NULL)
    {
        fprintf(stderr, "Could not open file \"%s\" for writing.\n", path);
        exit(74);
    }

    return fd;
}

void stringToLowercase(char* s)
{
    for(int32_t i = 0; s[i] != '\0'; i++)
    {
        s[i] = tolower(s[i]);
    }
}

char* intToHexString(uint64_t n, uint8_t bytes) // bits means the number of used bits in the number, so i dont create a new function for smaller integers
{
    char* str = (char*)malloc(2 * bytes * sizeof(char));

    if (snprintf(str, 2 * bytes + 2, "0x%x", n) != 2 * bytes + 2)
        return NULL;

    return str;
}

char* intToBinaryString(uint64_t n, uint8_t bytes) // bits means the number of used bits in the number, so i dont create a new function for smaller integers
{
    uint8_t len = 8 * bytes;
    char* str = (char*)malloc((len + 1) * sizeof(char));
    str[len] = '\0';

    for(int i = 0; i < len; i++)
    {
        str[i] = '0';
    }

    for(int i = len - 1; i >= 0 && n > 0; i--)
    {
        if(n & 1)
            str[i] = '1';
        else
            str[i] = '0';

        n >>= 1;
    }

    return str;
}

int64_t parseHexNumber(const char* str)
{
    unsigned int number;
    if (sscanf(str, "%x", &number) == 1)
        return number;

    return -1; // failed
}
