#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "common.h"

Instruction instructions[258] = 
{
    {   .name = "trap",     .arity = { 3, 2, 1}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 1},
                            { 1, 1, 1},
                            { 1, 1, 1}}},
    {   .name = "fcmp",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fun",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "feql",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fadd",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fix",      .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fsub",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fixu",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "flot",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "floti",    .arity = { 3, 2, 0}, .has_alt_ver = false, // ? is this correct
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "flotu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "flotui",   .arity = { 3, 2, 0}, .has_alt_ver = false, // ?
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "sflot",    .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sfloti",   .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "sflotu",   .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sflotui",  .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "fmul",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fcmpe",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fune",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "feqle",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fdiv",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fsqrt",    .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "frem",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "fint",     .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mul",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "muli",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mulu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "mului",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "div",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "divi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "divu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "divui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "add",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "addi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "addu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "addui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sub",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "subi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "subu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "subui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "2addu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "2addui",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "4addu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "4addui",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "8addu",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "8addui",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "16addu",   .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "16addui",  .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmp",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmpi",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmpu",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "cmpui",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "neg",      .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "negi",     .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "negu",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "negui",    .arity = { 3, 2, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 1},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "SL",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SLI",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SLU",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SLUI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SR",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SRI",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SRU",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SRUI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BN",       .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNB",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BZ",       .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BZB",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BP",       .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BPB",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BOD",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BODB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNN",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNNB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNZ",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNZB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNP",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BNPB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BEV",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BEVB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBN",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBZ",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBZB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBP",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBPB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBOD",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBODB",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNN",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNNB",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNZ",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNZB",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNP",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBNPB",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBEV",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PBEVB",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSN",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSZ",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSZI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSP",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSPI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSOD",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSODI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNN",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNNI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNZ",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNZI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNP",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSNPI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    { .name = "CSEV",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSEVI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSN",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSZ",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSZI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSP",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSPI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSOD",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSODI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNN",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNNI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNZ",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNZI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNP",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSNPI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSEV",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ZSEVI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDB",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDBI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDBU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDBUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDW",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDWI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDWU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDWUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDT",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDTI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDTU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDTUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDO",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDOI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDOU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDOUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDSF",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "LDSFI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDHT",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "LDHTI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSWAP",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "CSWAPI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDUNC",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDUNCI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDVTS",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "LDVTSI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PRELD",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PRELDI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PREGO",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PREGOI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "GO",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "GOI",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STB",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STBI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STBU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STBUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STW",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STWI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STWU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STWUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STT",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STTI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STTU",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STTUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STO",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STOI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    { .name = "STOU",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STOUI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STSF",     .arity = { 3, 2, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 1, 0},
                            { 0, 0, 0}}},
    {   .name = "STSFI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STHT",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STHTI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STCO",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STCOI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STUNC",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "STUNCI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SYNCD",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SYNCDI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PREST",    .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PRESTI",   .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SYNCID",   .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SYNCIDI",  .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PUSHGO",   .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PUSHGOI",  .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "OR",       .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORI",      .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORN",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORNI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "NOR",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "NORI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "XOR",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "XORI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "AND",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDN",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDNI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "NAND",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "NANDI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "NXOR",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "NXORI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BDIF",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "BDIFI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "WDIF",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "WDIFI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "TDIF",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "TDIFI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ODIF",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ODIFI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "MUX",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "MUXI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SADD",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SADDI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "MOR",      .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "MORI",     .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "MXOR",     .arity = { 3, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "MXORI",    .arity = { 3, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SETH",     .arity = { 2, 0 ,0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SETMH",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SETML",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "SETL",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "INCH",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "INCMH",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "INCML",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "INCL",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORH",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORMH",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORML",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ORL",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDNH",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDNMH",   .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDNML",   .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "ANDNL",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "JMP",      .arity = { 1, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "JMPB",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PUSHJ",    .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PUSHJB",   .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "GETA",     .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "GETAB",    .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PUT",      .arity = { 2, 0, 0}, .has_alt_ver = true,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "PUTI",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "POP",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "RESUME",   .arity = { 1, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "save",     .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}}, // ?
    {   .name = "unsave",   .arity = { 1, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "sync",     .arity = { 1, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 1, 0, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "swym",     .arity = {3, 2, 1}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 1},
                            { 1, 1, 0},
                            { 1, 0, 0}}}, // NOP
    {   .name = "get",      .arity = { 2, 0, 0}, .has_alt_ver = false,
        .is_constant = {    { 0, 1, 0},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "trip",     .arity = {3, 2, 1}, .has_alt_ver = false,
        .is_constant = {    { 1, 1, 1},
                            { 1, 1, 0},
                            { 1, 0, 0}}},
    {   .name = "lda",      .arity = {3, 0, 0}, .has_alt_ver = false, 
        .is_constant = {    { 1, 1, 1},
                            { 0, 0, 0},
                            { 0, 0, 0}}},
    {   .name = "set",      .arity = {2, 2, 0}, .has_alt_ver = false,
        .is_constant = {    {1, 0, 0},
                            {1, 1, 0},
                            {0, 0, 0}}},
};

int32_t parseNumber(char* buffer)
{
    int32_t number = 0;

    if (sscanf(buffer, "%d", &number) == 1)
        return number;

    return -1;
}

char* getString(char* buffer, int32_t length, int32_t buf_index)
{
    if(length <= 1)
        return NULL;
    
    int32_t i = 0;
    char* new_string = (char*)malloc(length * sizeof(char));
    new_string[length - 1] = '\0';
    for(; (i + 1 - length) != 0; i++)
    {
        new_string[i]   = buffer[buf_index - length + 1 + i];   
    }

    return new_string;
}

char* readFile(const char* path)
{
    FILE* fd = fopen(path, "rb");
    if(fd == NULL)
    {
        fprintf(stderr, "Could not open file \"%s\" for reading.\n", path);
        exit(74);
    }

    fseek(fd, 0L, SEEK_END);
    size_t file_size = ftell(fd);
    rewind(fd);

    char* buffer = (char*)malloc(file_size + 1);
    if(buffer == NULL)
    {
        fprintf(stderr, "Not enough memory to read \"%s\".\n", path);
        exit(74);
    }

    size_t bytes_read = fread(buffer, sizeof(char), file_size, fd);
    if (bytes_read < file_size)
    {
        fprintf(stderr, "Could not read file \"%s\".\n", path);
        exit(74);
    }

    buffer[bytes_read] = '\0';

    fclose(fd);
    return buffer;
}

FILE* createFile(const char* path)
{
    FILE* fd = fopen(path, "w");
    if (fd == NULL)
    {
        fprintf(stderr, "Could not open file \"%s\" for writing.\n", path);
        exit(74);
    }

    return fd;
}

void stringToLowercase(char* s)
{
    for(int32_t i = 0; s[i] != '\0'; i++)
    {
        s[i] = tolower(s[i]);
    }
}

char* intToHexString(uint64_t n, uint8_t bytes) // bits means the number of used bits in the number, so i dont create a new function for smaller integers
{
    char* str = (char*)malloc(2 * bytes * sizeof(char));

    if (snprintf(str, 2 * bytes + 2, "0x%x", n) != 2 * bytes + 2)
        return NULL;

    return str;
}

char* intToBinaryString(uint64_t n, uint8_t bytes) // bits means the number of used bits in the number, so i dont create a new function for smaller integers
{
    uint8_t len = 8 * bytes;
    char* str = (char*)malloc((len + 1) * sizeof(char));
    str[len] = '\0';

    for(int i = 0; i < len; i++)
    {
        str[i] = '0';
    }

    for(int i = len - 1; i >= 0 && n > 0; i--)
    {
        if(n & 1)
            str[i] = '1';
        else
            str[i] = '0';

        n >>= 1;
    }

    return str;
}

int64_t parseHexNumber(const char* str)
{
    unsigned int number;
    if (sscanf(str, "%x", &number) == 1)
        return number;

    return -1; // failed
}
