CC = gcc
CFLAGS = -g
CPPFLAGS = 
mmix-assembler: main.c parser.h parser.c scanner.h scanner.c common.h common.c trie.h trie.c table.h table.c debug.h debug.c 
	gcc main.c parser.h parser.c scanner.h scanner.c common.h common.c trie.h trie.c table.h table.c debug.h debug.c -o mmix-assembler
